name: build

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake --preset Debug && cmake --build --preset Debug
