name: Build & Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        compiler: [{ c: gcc, cxx: g++ }, { c: clang, cxx: clang++ }]

    name: Build & Test
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message , 'ci-skip') }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        env:
          CC: ${{ matrix.compiler.c }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          cmake --preset ${{ matrix.configuration }}
          cmake --build --preset default
          ctest --preset default
