name: linting

on:
  workflow_dispatch:
  push:
    branches:
      ["main"]
  pull_request:
    branches:
      ["main"]

jobs:
  build:
    name: Pre-Commit Linting
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
            cache: pip
            cache-dependency-path: 'requirements.txt'

        - name: Install pre-commit
          run: python3 -m pip install pre-commit

        - name: Run pre-commit
          run: pre-commit run --all-files --color=always --show-diff-on-failure
