name: Linting

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message , 'ci skip') }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "requirements.txt"

      - name: Install pre-commit
        run: python3 -m pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --color=always --show-diff-on-failure

      - name: Install CppCheck
        run: |
          git clone --branch 2.14.2 https://github.com/danmar/cppcheck.git
          cd cppcheck/
          cmake -B build/ -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DBUILD_GUI=OFF \
            -DUSE_MATCHCOMPILER=ON \
            -DBUILD_TESTS=OFF
          cmake --build build/ --parallel
          sudo cmake --install build/

      - name: Run CppCheck
        run: bash scripts/cppcheck.sh
